In [13]:
import torch
from torch import nn
from torchvision import transforms
from torchvision.datasets import ImageFolder
from util import accuracy


In [30]:
from collections import defaultdict


# We want to evaluate the test accuracy of the overall performance, the in race perform, and the other race
# How? 
#
#
#
#

def accuracy(output, target, topk=(1,)):
    """Computes the accuracy over the k top predictions for the specified values of k"""
    with torch.no_grad():
        maxk = max(topk)
        batch_size = target.size(0)

        _, pred = output.topk(maxk, 1, True, True)
        pred = pred.t()
        correct = pred.eq(target.view(1, -1).expand_as(pred))

        res = []
        for k in topk:
            correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True)
            res.append(correct_k.mul_(100.0 / batch_size))
        return res
    
def accuracy_by_race(output, target, dataset, topk=(1,)):
    """Computes the accuracy over the k top predictions for the specified values of k"""
    with torch.no_grad():
        maxk = max(topk)
        batch_size = target.size(0)

        _, pred = output.topk(maxk, 1, True, True)
        pred = pred.t()
        correct = pred.eq(target.view(1, -1).expand_as(pred))

        # Initialize a dictionary to hold accuracies for each race
        accuracies = defaultdict(list)

        for k in topk:
            correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True)
            accuracy_k = correct_k.mul_(100.0 / batch_size)

            # Record accuracy for each race
            for i in range(batch_size):
                race = dataset.classes[target[i]]
                accuracies[race].append(accuracy_k[i])

        return accuracies



In [31]:
# Define your output tensor and target tensor
output = torch.tensor([[0.1, 0.2, 0.7], [0.8, 0.1, 0.1]])
target = torch.tensor([2, 0])

# Call the accuracy function
result = accuracy(output, target, topk=(1,2))

# Print the result
print(result)

[tensor([100.]), tensor([100.])]


In [32]:
from torchvision.datasets import ImageFolder
import torch


def accuracy_by_race(output, target, dataset, topk=(1,)):
    """Computes the accuracy over the k top predictions for the specified values of k"""
    with torch.no_grad():
        maxk = max(topk)
        batch_size = target.size(0)

        _, pred = output.topk(maxk, 1, True, True)
        pred = pred.t()
        correct = pred.eq(target.view(1, -1).expand_as(pred))

        # Initialize a dictionary to hold accuracies for each race
        accuracies = defaultdict(list)

        for k in topk:
            correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True)
            accuracy_k = correct_k.mul_(100.0 / batch_size)

            # Record accuracy for each race
            for i in range(batch_size):
                race = dataset.classes[target[i]]
                accuracies[race].append(accuracy_k[i])

        return accuracies


In [34]:


# Define your output tensor and target tensor
output = torch.tensor([[0.1, 0.2, 0.7], [0.8, 0.1, 0.1]])
target = torch.tensor([2, 0])

# Create a mock dataset with class labels corresponding to races
dataset = ImageFolder(root='./test/')
dataset.classes = ['race1', 'race2', 'race3']
dataset.class_to_idx = {'race1': 0, 'race2': 1, 'race3': 2}

# Call the accuracy_by_race function
accuracies = accuracy_by_race(output, target, dataset, topk=(1,2))
print(accuracies)

# Print the accuracies for each race
for race, accuracy in accuracies.items():
    print(f'Accuracy for {race}: {sum(accuracy)/len(accuracy)}')


IndexError: index 1 is out of bounds for dimension 0 with size 1

In [25]:
import torch

# Create some sample data
output = torch.randn(32, )  # Sample output tensor, 5 samples, 3 classes
target = torch.tensor([1, 2, 0, 2, 1])  # Sample target tensor, ground truth labels

# Call the accuracy function
top1, top5 = accuracy(output, target, topk=(1, 5))

print(f"Top-1 Accuracy: {top1.item():.2f}%")
print(f"Top-5 Accuracy: {top5.item():.2f}%")

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [2]:
!pip install torchvision

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.2.1 -> 23.3
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip


In [4]:
import torch
print(torch.randn(8, 5))

tensor([[ 0.5560, -1.4274, -0.2668, -0.0637, -1.0900],
        [ 1.4864, -0.0651,  0.1268,  0.4204, -0.2589],
        [ 0.4242, -0.0728,  0.4617, -0.8344,  0.3453],
        [-0.3346,  0.2447,  0.3663, -1.8127, -0.4779],
        [-1.0697, -0.2619, -0.4329, -0.8537, -0.1789],
        [ 1.3182, -1.8663,  0.2477, -0.1045,  0.5833],
        [ 0.0652, -0.2209, -1.3188, -1.5880,  0.2209],
        [ 1.7836,  0.8594,  1.0216, -0.1526,  0.1906]])


In [6]:
#test data loader

import torch
import torchvision
from torchvision import transforms, datasets

def set_loader(data_folder, batch_size): 
    input_shape = (3, 128, 128)

    train_transform = transforms.Compose([
            transforms.Resize(int(input_shape[1] * 156 / 128)),
            transforms.RandomCrop(input_shape[1:]),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.5, 0.5, 0.5],
                            std=[0.5, 0.5, 0.5])
        ])  

    #assume two crop is not relevant 
    train_dataset = datasets.ImageFolder(
        root=data_folder,
        transform=train_transform
    )

    train_sampler = None
    train_loader = torch.utils.data.DataLoader(
        train_dataset, batch_size=batch_size, shuffle=(train_sampler is None),
        pin_memory=True, sampler=train_sampler)

    print("train_loader length: ", len(train_loader))

    return train_loader

In [8]:
train_folder = "./data/test/African/"
train_loader = set_loader(train_folder, 8)

train_loader length:  750


In [21]:
pred = torch.randint(0, 500, (8,3))


In [29]:
#randome int of batch size 8, from 500 classes

topk = (1,5)
batch_size = 8
pred = torch.tensor([[402,  55, 366, 240, 440, 440, 418,  55],
        [416, 108,  75, 366, 192, 309, 402, 108],
        [129, 314, 197, 190, 486, 154, 355,  23],
        [428,  75, 414, 341,  44, 143, 428, 314],
        [ 81, 240, 320, 176, 416, 416, 201, 492]])
print(pred, pred.shape)

for idx, (data, target) in enumerate(train_loader):

    pred = pred.t()
    target = target.view(-1, 1)
    print(target, target.shape)
    target = target.expand_as(pred)
    print(target, target.shape)

    correct = pred.eq(target)
    print(correct)

    res = []
    for k in topk:
        correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True)
        print(correct_k)
        res.append(correct_k.mul_(100.0 / batch_size))
    
    print(res)
    break 

    # print(idx, data.shape, target.shape)

tensor([[402,  55, 366, 240, 440, 440, 418,  55],
        [416, 108,  75, 366, 192, 309, 402, 108],
        [129, 314, 197, 190, 486, 154, 355,  23],
        [428,  75, 414, 341,  44, 143, 428, 314],
        [ 81, 240, 320, 176, 416, 416, 201, 492]]) torch.Size([5, 8])
tensor([[262],
        [423],
        [177],
        [429],
        [472],
        [214],
        [155],
        [240]]) torch.Size([8, 1])
tensor([[262, 262, 262, 262, 262],
        [423, 423, 423, 423, 423],
        [177, 177, 177, 177, 177],
        [429, 429, 429, 429, 429],
        [472, 472, 472, 472, 472],
        [214, 214, 214, 214, 214],
        [155, 155, 155, 155, 155],
        [240, 240, 240, 240, 240]]) torch.Size([8, 5])
tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, Fals

In [30]:
res = []
correct = torch.tensor([True, False, False, False, False, False, False, False],
                       [False, False, False, False, False, False, False, False],
                       [True, False, False, False, False, False, False, False])
for k in topk:
    print(correct[:k])
    print(correct[:k].shape)
    print(correct[:k].reshape(-1))
    print(correct[:k].reshape(-1).float().sum(0, keepdim=True))
    print(correct[:k].view(-1))
    correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True)
    res.append(correct_k.mul_(100.0 / batch_size))
print(res)

tensor([True])
torch.Size([1])
tensor([True])
tensor([1.])
tensor([True])
tensor([ True, False, False, False, False])
torch.Size([5])
tensor([ True, False, False, False, False])
tensor([1.])
tensor([ True, False, False, False, False])
[tensor([12.5000]), tensor([12.5000])]


In [35]:

def validate(val_loader, model, classifier, criterion, opt, class_to_idx):
    """Validation"""
    model.eval()
    classifier.eval()

    batch_time = AverageMeter()
    losses = AverageMeter()
    top1 = AverageMeter()
    class_to_idx = val_loader.class_to_idx

    

    # Create dictionaries to store accuracy by race
    race_acc = {}
    
    with torch.no_grad():
        end = time.time()
        for idx, (images, labels) in enumerate(val_loader):
            images = images.float().cuda()
            labels = labels.cuda()
            bsz = labels.shape[0]

            # Forward pass
            output = classifier(model.encoder(images))
            loss = criterion(output, labels)

            # Update metric
            losses.update(loss.item(), bsz)
            acc1, acc5 = accuracy(output, labels, topk=(1, 5))
            top1.update(acc1[0], bsz)

            # Measure elapsed time
            batch_time.update(time.time() - end)
            end = time.time()

            # Group predictions and labels by race
            for i in range(bsz):
                label = labels[i].item()
                predicted_class = output[i].argmax().item()
                race = class_to_idx[label]

                if race not in race_acc:
                    race_acc[race] = AverageMeter()

                race_acc[race].update(int(predicted_class == label), 1)

            if idx % opt.print_freq == 0:
                print('Test: [{0}/{1}]\t'
                      'Time {batch_time.val:.3f} ({batch_time.avg:.3f})\t'
                      'Loss {loss.val:.4f} ({loss.avg:.4f})\t'
                      'Acc@1 {top1.val:.3f} ({top1.avg:.3f})'.format(
                       idx, len(val_loader), batch_time=batch_time,
                       loss=losses, top1=top1))

    print(' * Acc@1 {top1.avg:.3f}'.format(top1=top1))

    # Print accuracy by race
    for race, acc_meter in race_acc.items():
        print(f'Race {race}: Acc@1 {acc_meter.avg:.3f}')

    return losses.avg, top1.avg


In [26]:
from main_linear import set_loader
class Opt:
    def __init__(self, val_folder, batch_size, num_workers, train_folder=None, model='resnet50', n_cls=4, ckpt='./path/to/your/ckpt/model.ckpt'):
        self.val_folder = val_folder
        self.batch_size = batch_size
        self.num_workers = num_workers
        self.train_folder = train_folder
        self.model = model
        self.n_cls = n_cls
        self.ckpt = ckpt


opt = Opt(val_folder='./data/linear_prob_data/train/', batch_size=32, num_workers=4)
_, val_loader = set_loader(opt)
class_to_idx = val_loader.dataset.class_to_idx
class_to_idx



{'African': 0, 'Asian': 1, 'Caucasian': 2, 'Indian': 3}

from main_linear import set_loader
class Opt:
    def __init__(self, val_folder, batch_size, num_workers, train_folder=None):
        self.val_folder = val_folder
        self.batch_size = batch_size
        self.num_workers = num_workers
        self.train_folder = train_folder

opt = Opt(val_folder='./data/biased_african/train/', batch_size=32, num_workers=4)
_, val_loader = set_loader(opt)
class_to_idx = val_loader.dataset.class_to_idx
class_to_idx




{'African': 0, 'Asian': 1, 'Caucasian': 2, 'Indian': 3}


I now want to see how i can modify validate code to record accuracy by race collect to 
1. Overall performance
2. Inrace performance: Same race accuracy. Ex: We have 4 biased models and 1 of them is biased towards African dataset. We want to see just the perfomace on the African.
3. Out of race performance: Other race accuracy. Ex: We have 4 biased models and 1 of them is biased towards African dataset. We want to see just the perfomace on the non-African or the performance on the 3 other races.

Here is the validation and accuracy code, how would i modify them. I need to class_to_idx to track what inputs I am training on and what the validation is:



def validate(val_loader, model, classifier, criterion, opt):
    """validation"""
    model.eval()
    classifier.eval()

    batch_time = AverageMeter()
    losses = AverageMeter()
    top1 = AverageMeter()

    with torch.no_grad():
        end = time.time()
        for idx, (images, labels) in enumerate(val_loader):
            images = images.float().cuda()
            labels = labels.cuda()
            bsz = labels.shape[0]

            # forward
            output = classifier(model.encoder(images))
            loss = criterion(output, labels)

            # update metric
            losses.update(loss.item(), bsz)
            acc1, acc5 = accuracy(output, labels, topk=(1, 5))
            top1.update(acc1[0], bsz)

            # measure elapsed time
            batch_time.update(time.time() - end)
            end = time.time()

            if idx % opt.print_freq == 0:
                print('Test: [{0}/{1}]\t'
                      'Time {batch_time.val:.3f} ({batch_time.avg:.3f})\t'
                      'Loss {loss.val:.4f} ({loss.avg:.4f})\t'
                      'Acc@1 {top1.val:.3f} ({top1.avg:.3f})'.format(
                       idx, len(val_loader), batch_time=batch_time,
                       loss=losses, top1=top1))

    print(' * Acc@1 {top1.avg:.3f}'.format(top1=top1))
    return losses.avg, top1.avg

def accuracy(output, target, topk=(1,)):
    """Computes the accuracy over the k top predictions for the specified values of k"""
    with torch.no_grad():
        maxk = max(topk)
        batch_size = target.size(0)

        _, pred = output.topk(maxk, 1, True, True)
        pred = pred.t()
        correct = pred.eq(target.view(1, -1).expand_as(pred))

        res = []
        for k in topk:
            correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True)
            res.append(correct_k.mul_(100.0 / batch_size))
        return res

In [51]:
import torch
from util import AverageMeter, accuracy
import time

def validate(val_loader, model, classifier, criterion, opt, class_to_idx):
    """Validation"""
    # model.eval()
    # classifier.eval()

    batch_time = AverageMeter()
    losses = AverageMeter()
    top1 = AverageMeter()

    race_accuracies = {}  # Store accuracy by race
    in_race_accuracies = {}  # Store in-race accuracy
    out_of_race_accuracies = {}  # Store out-of-race accuracy

    with torch.no_grad():
        end = time.time()
        for idx, (images, labels) in enumerate(val_loader):
            images = images.float()
            labels = labels
            bsz = labels.shape[0]
            # Debugging print: Print images, labels, and batch size
            print(f'Batch {idx} - Images: {images.shape}, Labels: {labels.shape}, Batch Size: {bsz}')

            # Check the shape of labels
            print(f'Labels Shape: {labels.shape}')
            # Calculate the race for each image based on class labels
            race_labels = [k for k, v in class_to_idx.items() if v in labels]
            race_labels = []
            for k, v in class_to_idx.items():
                print(k)
                print(v)


                if v in labels:
                    race_labels.append(k)
            print(f'Race Labels: {race_labels}')

            return

            # Debugging print: Print the current batch index and batch size
            # Forward pass
            # output = classifier(model.encoder(images))  # Commented out the encoder part
            output = classifier(images)  # Assuming 'classifier' is appropriate for the task

            loss = criterion(output, labels)

            # Debugging print: Print the loss and accuracy for this batch
            print(f'Loss: {loss.item()}, Accuracy: {accuracy(output, labels)}')

            # Update metrics
            losses.update(loss.item(), bsz)
            acc1, _ = accuracy(output, labels, topk=(1, 5))
            top1.update(acc1, bsz)

            # Debugging print: Print the updated metrics
            print(f'Updated Loss: {losses.avg}, Updated Accuracy: {top1.avg}')

            # Calculate accuracy by race
            for race in race_labels:
                if race not in race_accuracies:
                    race_accuracies[race] = AverageMeter()
                race_accuracies[race].update(acc1, bsz)

            # Debugging print: Print accuracy by race
            print(f'Accuracy by Race: {race_accuracies}')

            # Measure elapsed time
            batch_time.update(time.time() - end)
            end = time.time()

            if idx % 10 == 0:
                print('Test: [{0}/{1}]\t'
                      'Time {batch_time.val:.3f} ({batch_time.avg:.3f})\t'
                      'Loss {loss.val:.4f} ({loss.avg:.4f})\t'
                      'Acc@1 {top1.val:.3f} ({top1.avg:.3f})'.format(
                       idx, len(val_loader), batch_time=batch_time,
                       loss=losses, top1=top1))

    print(' * Overall Acc@1 {top1.avg:.3f}'.format(top1=top1))

    # Calculate in-race and out-of-race accuracy
    for race, accuracy_meter in race_accuracies.items():
        in_race_acc = accuracy_meter.avg
        out_of_race_acc = (top1.avg * bsz - accuracy_meter.sum) / (bsz - accuracy_meter.count)
        in_race_accuracies[race] = in_race_acc
        out_of_race_accuracies[race] = out_of_race_acc

        # Debugging print: Print in-race and out-of-race accuracy
        print(f'In-Race Accuracy ({race}): {in_race_acc:.3f}')
        print(f'Out-of-Race Accuracy ({race}): {out_of_race_acc:.3f}')

    # Debugging print: Print the final accuracy results
    print(f'Final Loss: {losses.avg}, Final Accuracy: {top1.avg}')
    print(f'Final In-Race Accuracy: {in_race_accuracies}')
    print(f'Final Out-of-Race Accuracy: {out_of_race_accuracies}')

    return losses.avg, top1.avg, in_race_accuracies, out_of_race_accuracies


In [53]:
import torch
import torch.nn as nn
from torchvision import models
from main_linear import set_loader  # Replace with your actual data loader module
from networks.resnet_big import LinearClassifier
import torch
import torch.nn as nn
from networks.resnet_big import SupConResNet, LinearClassifier

def set_model(opt):
    model = SupConResNet(name=opt.model)
    criterion = torch.nn.CrossEntropyLoss()

    classifier = LinearClassifier(name=opt.model, num_classes=opt.n_cls)

    ckpt = torch.load(opt.ckpt, map_location='cpu')
    state_dict = ckpt['model']

    if torch.cuda.is_available():
        if torch.cuda.device_count() > 1:
            model.encoder = torch.nn.DataParallel(model.encoder)
        else:
            new_state_dict = {}
            # for k, v in state_dict.items():
            #     k = k.replace("module.", "")
            #     new_state_dict[k] = v
            # state_dict = new_state_dict
            # model = model.cuda()
            # classifier = classifier.cuda()
            # criterion = criterion.cuda()
            # cudnn.benchmark = True

        # model.load_state_dict(state_dict)
    else:
        print("GPU not available. Using CPU for inference.")
        model.load_state_dict(state_dict, map_location='cpu')

    return model, classifier, criterion


In [38]:
# Simulate the Opt object
class Opt:
    def __init__(self, val_folder, batch_size, num_workers, train_folder=None):
        self.val_folder = val_folder
        self.batch_size = batch_size
        self.num_workers = num_workers
        self.train_folder = train_folder

In [52]:
import torch
import torch.nn as nn
from torchvision import models
from main_linear import set_loader  # Replace with your actual data loader module
from networks.resnet_big import LinearClassifier
# Load your model and data loaders
# model = models.resnet50(pretrained=True)
# classifier = nn.Linear(2048, 4)  # Replace with your classifier architecture
# criterion = nn.CrossEntropyLoss()


opt = Opt(val_folder='./data/linear_prob_data/train/', batch_size=32, num_workers=4)

# Load the data loader
_, val_loader = set_loader(opt)

# Define class_to_idx based on your dataset
class_to_idx = {'African': 0, 'Asian': 1, 'Caucasian': 2, 'Indian': 3}
# Iterate through the small validation data loader and print labels
# for idx, (images, labels) in enumerate(val_loader):
#     print(f'Batch {idx} - Labels: {labels}')


# Create a small test dataset by taking the first N samples from the validation set
num_samples_to_test = 10  # Adjust this number as needed
small_val_loader = torch.utils.data.DataLoader(val_loader.dataset, batch_size=opt.batch_size, shuffle=True, num_workers=opt.num_workers)
small_val_loader.dataset.samples = small_val_loader.dataset.samples[:num_samples_to_test]

# Call the modified validate function with the small test dataset
loss, overall_accuracy, in_race_accuracies, out_of_race_accuracies = validate(val_loader, None, None, None, opt, class_to_idx)

# # Print the results
# print(f'Overall Accuracy: {overall_accuracy:.3f}')
# for race, in_race_acc in in_race_accuracies.items():
#     print(f'In-Race Accuracy ({race}): {in_race_acc:.3f}')
#     print(f'Out-of-Race Accuracy ({race}): {out_of_race_accuracies[race]:.3f}')

/Users/lorenzomendoza/anaconda3/envs/machinelearning/lib/python3.11/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/Users/lorenzomendoza/anaconda3/envs/machinelearning/lib/python3.11/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Batch 0 - Images: torch.Size([10, 3, 400, 400]), Labels: torch.Size([10]), Batch Size: 10
Labels Shape: torch.Size([10])
African
0
Asian
1
Caucasian
2
Indian
3
Race Labels: ['African']


TypeError: cannot unpack non-iterable NoneType object