In [13]:
import torch
from torch import nn
from torchvision import transforms
from torchvision.datasets import ImageFolder
from util import accuracy


In [30]:
from collections import defaultdict


# We want to evaluate the test accuracy of the overall performance, the in race perform, and the other race
# How? 
#
#
#
#

def accuracy(output, target, topk=(1,)):
    """Computes the accuracy over the k top predictions for the specified values of k"""
    with torch.no_grad():
        maxk = max(topk)
        batch_size = target.size(0)

        _, pred = output.topk(maxk, 1, True, True)
        pred = pred.t()
        correct = pred.eq(target.view(1, -1).expand_as(pred))

        res = []
        for k in topk:
            correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True)
            res.append(correct_k.mul_(100.0 / batch_size))
        return res
    
def accuracy_by_race(output, target, dataset, topk=(1,)):
    """Computes the accuracy over the k top predictions for the specified values of k"""
    with torch.no_grad():
        maxk = max(topk)
        batch_size = target.size(0)

        _, pred = output.topk(maxk, 1, True, True)
        pred = pred.t()
        correct = pred.eq(target.view(1, -1).expand_as(pred))

        # Initialize a dictionary to hold accuracies for each race
        accuracies = defaultdict(list)

        for k in topk:
            correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True)
            accuracy_k = correct_k.mul_(100.0 / batch_size)

            # Record accuracy for each race
            for i in range(batch_size):
                race = dataset.classes[target[i]]
                accuracies[race].append(accuracy_k[i])

        return accuracies



In [31]:
# Define your output tensor and target tensor
output = torch.tensor([[0.1, 0.2, 0.7], [0.8, 0.1, 0.1]])
target = torch.tensor([2, 0])

# Call the accuracy function
result = accuracy(output, target, topk=(1,2))

# Print the result
print(result)

[tensor([100.]), tensor([100.])]


In [32]:
from torchvision.datasets import ImageFolder
import torch


def accuracy_by_race(output, target, dataset, topk=(1,)):
    """Computes the accuracy over the k top predictions for the specified values of k"""
    with torch.no_grad():
        maxk = max(topk)
        batch_size = target.size(0)

        _, pred = output.topk(maxk, 1, True, True)
        pred = pred.t()
        correct = pred.eq(target.view(1, -1).expand_as(pred))

        # Initialize a dictionary to hold accuracies for each race
        accuracies = defaultdict(list)

        for k in topk:
            correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True)
            accuracy_k = correct_k.mul_(100.0 / batch_size)

            # Record accuracy for each race
            for i in range(batch_size):
                race = dataset.classes[target[i]]
                accuracies[race].append(accuracy_k[i])

        return accuracies


In [34]:


# Define your output tensor and target tensor
output = torch.tensor([[0.1, 0.2, 0.7], [0.8, 0.1, 0.1]])
target = torch.tensor([2, 0])

# Create a mock dataset with class labels corresponding to races
dataset = ImageFolder(root='./test/')
dataset.classes = ['race1', 'race2', 'race3']
dataset.class_to_idx = {'race1': 0, 'race2': 1, 'race3': 2}

# Call the accuracy_by_race function
accuracies = accuracy_by_race(output, target, dataset, topk=(1,2))
print(accuracies)

# Print the accuracies for each race
for race, accuracy in accuracies.items():
    print(f'Accuracy for {race}: {sum(accuracy)/len(accuracy)}')


IndexError: index 1 is out of bounds for dimension 0 with size 1

In [25]:
import torch

# Create some sample data
output = torch.randn(32, )  # Sample output tensor, 5 samples, 3 classes
target = torch.tensor([1, 2, 0, 2, 1])  # Sample target tensor, ground truth labels

# Call the accuracy function
top1, top5 = accuracy(output, target, topk=(1, 5))

print(f"Top-1 Accuracy: {top1.item():.2f}%")
print(f"Top-5 Accuracy: {top5.item():.2f}%")

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [2]:
!pip install torchvision

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.2.1 -> 23.3
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip


In [4]:
import torch
print(torch.randn(8, 5))

tensor([[ 0.5560, -1.4274, -0.2668, -0.0637, -1.0900],
        [ 1.4864, -0.0651,  0.1268,  0.4204, -0.2589],
        [ 0.4242, -0.0728,  0.4617, -0.8344,  0.3453],
        [-0.3346,  0.2447,  0.3663, -1.8127, -0.4779],
        [-1.0697, -0.2619, -0.4329, -0.8537, -0.1789],
        [ 1.3182, -1.8663,  0.2477, -0.1045,  0.5833],
        [ 0.0652, -0.2209, -1.3188, -1.5880,  0.2209],
        [ 1.7836,  0.8594,  1.0216, -0.1526,  0.1906]])


In [6]:
#test data loader

import torch
import torchvision
from torchvision import transforms, datasets

def set_loader(data_folder, batch_size): 
    input_shape = (3, 128, 128)

    train_transform = transforms.Compose([
            transforms.Resize(int(input_shape[1] * 156 / 128)),
            transforms.RandomCrop(input_shape[1:]),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.5, 0.5, 0.5],
                            std=[0.5, 0.5, 0.5])
        ])  

    #assume two crop is not relevant 
    train_dataset = datasets.ImageFolder(
        root=data_folder,
        transform=train_transform
    )

    train_sampler = None
    train_loader = torch.utils.data.DataLoader(
        train_dataset, batch_size=batch_size, shuffle=(train_sampler is None),
        pin_memory=True, sampler=train_sampler)

    print("train_loader length: ", len(train_loader))

    return train_loader

In [8]:
train_folder = "./data/test/African/"
train_loader = set_loader(train_folder, 8)

train_loader length:  750


In [21]:
pred = torch.randint(0, 500, (8,3))


In [29]:
#randome int of batch size 8, from 500 classes

topk = (1,5)
batch_size = 8
pred = torch.tensor([[402,  55, 366, 240, 440, 440, 418,  55],
        [416, 108,  75, 366, 192, 309, 402, 108],
        [129, 314, 197, 190, 486, 154, 355,  23],
        [428,  75, 414, 341,  44, 143, 428, 314],
        [ 81, 240, 320, 176, 416, 416, 201, 492]])
print(pred, pred.shape)

for idx, (data, target) in enumerate(train_loader):

    pred = pred.t()
    target = target.view(-1, 1)
    print(target, target.shape)
    target = target.expand_as(pred)
    print(target, target.shape)

    correct = pred.eq(target)
    print(correct)

    res = []
    for k in topk:
        correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True)
        print(correct_k)
        res.append(correct_k.mul_(100.0 / batch_size))
    
    print(res)
    break 

    # print(idx, data.shape, target.shape)

tensor([[402,  55, 366, 240, 440, 440, 418,  55],
        [416, 108,  75, 366, 192, 309, 402, 108],
        [129, 314, 197, 190, 486, 154, 355,  23],
        [428,  75, 414, 341,  44, 143, 428, 314],
        [ 81, 240, 320, 176, 416, 416, 201, 492]]) torch.Size([5, 8])
tensor([[262],
        [423],
        [177],
        [429],
        [472],
        [214],
        [155],
        [240]]) torch.Size([8, 1])
tensor([[262, 262, 262, 262, 262],
        [423, 423, 423, 423, 423],
        [177, 177, 177, 177, 177],
        [429, 429, 429, 429, 429],
        [472, 472, 472, 472, 472],
        [214, 214, 214, 214, 214],
        [155, 155, 155, 155, 155],
        [240, 240, 240, 240, 240]]) torch.Size([8, 5])
tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, Fals

In [30]:
res = []
correct = torch.tensor([True, False, False, False, False, False, False, False],
                       [False, False, False, False, False, False, False, False],
                       [True, False, False, False, False, False, False, False])
for k in topk:
    print(correct[:k])
    print(correct[:k].shape)
    print(correct[:k].reshape(-1))
    print(correct[:k].reshape(-1).float().sum(0, keepdim=True))
    print(correct[:k].view(-1))
    correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True)
    res.append(correct_k.mul_(100.0 / batch_size))
print(res)

tensor([True])
torch.Size([1])
tensor([True])
tensor([1.])
tensor([True])
tensor([ True, False, False, False, False])
torch.Size([5])
tensor([ True, False, False, False, False])
tensor([1.])
tensor([ True, False, False, False, False])
[tensor([12.5000]), tensor([12.5000])]


In [35]:

def validate(val_loader, model, classifier, criterion, opt, class_to_idx):
    """Validation"""
    model.eval()
    classifier.eval()

    batch_time = AverageMeter()
    losses = AverageMeter()
    top1 = AverageMeter()
    class_to_idx = val_loader.class_to_idx

    

    # Create dictionaries to store accuracy by race
    race_acc = {}
    
    with torch.no_grad():
        end = time.time()
        for idx, (images, labels) in enumerate(val_loader):
            images = images.float().cuda()
            labels = labels.cuda()
            bsz = labels.shape[0]

            # Forward pass
            output = classifier(model.encoder(images))
            loss = criterion(output, labels)

            # Update metric
            losses.update(loss.item(), bsz)
            acc1, acc5 = accuracy(output, labels, topk=(1, 5))
            top1.update(acc1[0], bsz)

            # Measure elapsed time
            batch_time.update(time.time() - end)
            end = time.time()

            # Group predictions and labels by race
            for i in range(bsz):
                label = labels[i].item()
                predicted_class = output[i].argmax().item()
                race = class_to_idx[label]

                if race not in race_acc:
                    race_acc[race] = AverageMeter()

                race_acc[race].update(int(predicted_class == label), 1)

            if idx % opt.print_freq == 0:
                print('Test: [{0}/{1}]\t'
                      'Time {batch_time.val:.3f} ({batch_time.avg:.3f})\t'
                      'Loss {loss.val:.4f} ({loss.avg:.4f})\t'
                      'Acc@1 {top1.val:.3f} ({top1.avg:.3f})'.format(
                       idx, len(val_loader), batch_time=batch_time,
                       loss=losses, top1=top1))

    print(' * Acc@1 {top1.avg:.3f}'.format(top1=top1))

    # Print accuracy by race
    for race, acc_meter in race_acc.items():
        print(f'Race {race}: Acc@1 {acc_meter.avg:.3f}')

    return losses.avg, top1.avg


In [26]:
from main_linear import set_loader
class Opt:
    def __init__(self, val_folder, batch_size, num_workers, train_folder=None, model='resnet50', n_cls=4, ckpt='./path/to/your/ckpt/model.ckpt'):
        self.val_folder = val_folder
        self.batch_size = batch_size
        self.num_workers = num_workers
        self.train_folder = train_folder
        self.model = model
        self.n_cls = n_cls
        self.ckpt = ckpt


opt = Opt(val_folder='./data/linear_prob_data/train/', batch_size=32, num_workers=4)
_, val_loader = set_loader(opt)
class_to_idx = val_loader.dataset.class_to_idx
class_to_idx



{'African': 0, 'Asian': 1, 'Caucasian': 2, 'Indian': 3}

from main_linear import set_loader
class Opt:
    def __init__(self, val_folder, batch_size, num_workers, train_folder=None):
        self.val_folder = val_folder
        self.batch_size = batch_size
        self.num_workers = num_workers
        self.train_folder = train_folder

opt = Opt(val_folder='./data/biased_african/train/', batch_size=32, num_workers=4)
_, val_loader = set_loader(opt)
class_to_idx = val_loader.dataset.class_to_idx
class_to_idx




{'African': 0, 'Asian': 1, 'Caucasian': 2, 'Indian': 3}


I now want to see how i can modify validate code to record accuracy by race collect to 
1. Overall performance
2. Inrace performance: Same race accuracy. Ex: We have 4 biased models and 1 of them is biased towards African dataset. We want to see just the perfomace on the African.
3. Out of race performance: Other race accuracy. Ex: We have 4 biased models and 1 of them is biased towards African dataset. We want to see just the perfomace on the non-African or the performance on the 3 other races.

Here is the validation and accuracy code, how would i modify them. I need to class_to_idx to track what inputs I am training on and what the validation is:



def validate(val_loader, model, classifier, criterion, opt):
    """validation"""
    model.eval()
    classifier.eval()

    batch_time = AverageMeter()
    losses = AverageMeter()
    top1 = AverageMeter()

    with torch.no_grad():
        end = time.time()
        for idx, (images, labels) in enumerate(val_loader):
            images = images.float().cuda()
            labels = labels.cuda()
            bsz = labels.shape[0]

            # forward
            output = classifier(model.encoder(images))
            loss = criterion(output, labels)

            # update metric
            losses.update(loss.item(), bsz)
            acc1, acc5 = accuracy(output, labels, topk=(1, 5))
            top1.update(acc1[0], bsz)

            # measure elapsed time
            batch_time.update(time.time() - end)
            end = time.time()

            if idx % opt.print_freq == 0:
                print('Test: [{0}/{1}]\t'
                      'Time {batch_time.val:.3f} ({batch_time.avg:.3f})\t'
                      'Loss {loss.val:.4f} ({loss.avg:.4f})\t'
                      'Acc@1 {top1.val:.3f} ({top1.avg:.3f})'.format(
                       idx, len(val_loader), batch_time=batch_time,
                       loss=losses, top1=top1))

    print(' * Acc@1 {top1.avg:.3f}'.format(top1=top1))
    return losses.avg, top1.avg

def accuracy(output, target, topk=(1,)):
    """Computes the accuracy over the k top predictions for the specified values of k"""
    with torch.no_grad():
        maxk = max(topk)
        batch_size = target.size(0)

        _, pred = output.topk(maxk, 1, True, True)
        pred = pred.t()
        correct = pred.eq(target.view(1, -1).expand_as(pred))

        res = []
        for k in topk:
            correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True)
            res.append(correct_k.mul_(100.0 / batch_size))
        return res

In [51]:
import torch
from util import AverageMeter, accuracy
import time

def validate(val_loader, model, classifier, criterion, opt, class_to_idx):
    """Validation"""
    # model.eval()
    # classifier.eval()

    batch_time = AverageMeter()
    losses = AverageMeter()
    top1 = AverageMeter()

    race_accuracies = {}  # Store accuracy by race
    in_race_accuracies = {}  # Store in-race accuracy
    out_of_race_accuracies = {}  # Store out-of-race accuracy

    with torch.no_grad():
        end = time.time()
        for idx, (images, labels) in enumerate(val_loader):
            images = images.float()
            labels = labels
            bsz = labels.shape[0]
            # Debugging print: Print images, labels, and batch size
            print(f'Batch {idx} - Images: {images.shape}, Labels: {labels.shape}, Batch Size: {bsz}')

            # Check the shape of labels
            print(f'Labels Shape: {labels.shape}')
            # Calculate the race for each image based on class labels
            race_labels = [k for k, v in class_to_idx.items() if v in labels]
            race_labels = []
            for k, v in class_to_idx.items():
                print(k)
                print(v)


                if v in labels:
                    race_labels.append(k)
            print(f'Race Labels: {race_labels}')

            return

            # Debugging print: Print the current batch index and batch size
            # Forward pass
            # output = classifier(model.encoder(images))  # Commented out the encoder part
            output = classifier(images)  # Assuming 'classifier' is appropriate for the task

            loss = criterion(output, labels)

            # Debugging print: Print the loss and accuracy for this batch
            print(f'Loss: {loss.item()}, Accuracy: {accuracy(output, labels)}')

            # Update metrics
            losses.update(loss.item(), bsz)
            acc1, _ = accuracy(output, labels, topk=(1, 5))
            top1.update(acc1, bsz)

            # Debugging print: Print the updated metrics
            print(f'Updated Loss: {losses.avg}, Updated Accuracy: {top1.avg}')

            # Calculate accuracy by race
            for race in race_labels:
                if race not in race_accuracies:
                    race_accuracies[race] = AverageMeter()
                race_accuracies[race].update(acc1, bsz)

            # Debugging print: Print accuracy by race
            print(f'Accuracy by Race: {race_accuracies}')

            # Measure elapsed time
            batch_time.update(time.time() - end)
            end = time.time()

            if idx % 10 == 0:
                print('Test: [{0}/{1}]\t'
                      'Time {batch_time.val:.3f} ({batch_time.avg:.3f})\t'
                      'Loss {loss.val:.4f} ({loss.avg:.4f})\t'
                      'Acc@1 {top1.val:.3f} ({top1.avg:.3f})'.format(
                       idx, len(val_loader), batch_time=batch_time,
                       loss=losses, top1=top1))

    print(' * Overall Acc@1 {top1.avg:.3f}'.format(top1=top1))

    # Calculate in-race and out-of-race accuracy
    for race, accuracy_meter in race_accuracies.items():
        in_race_acc = accuracy_meter.avg
        out_of_race_acc = (top1.avg * bsz - accuracy_meter.sum) / (bsz - accuracy_meter.count)
        in_race_accuracies[race] = in_race_acc
        out_of_race_accuracies[race] = out_of_race_acc

        # Debugging print: Print in-race and out-of-race accuracy
        print(f'In-Race Accuracy ({race}): {in_race_acc:.3f}')
        print(f'Out-of-Race Accuracy ({race}): {out_of_race_acc:.3f}')

    # Debugging print: Print the final accuracy results
    print(f'Final Loss: {losses.avg}, Final Accuracy: {top1.avg}')
    print(f'Final In-Race Accuracy: {in_race_accuracies}')
    print(f'Final Out-of-Race Accuracy: {out_of_race_accuracies}')

    return losses.avg, top1.avg, in_race_accuracies, out_of_race_accuracies


In [53]:
import torch
import torch.nn as nn
from torchvision import models
from main_linear import set_loader  # Replace with your actual data loader module
from networks.resnet_big import LinearClassifier
import torch
import torch.nn as nn
from networks.resnet_big import SupConResNet, LinearClassifier

def set_model(opt):
    model = SupConResNet(name=opt.model)
    criterion = torch.nn.CrossEntropyLoss()

    classifier = LinearClassifier(name=opt.model, num_classes=opt.n_cls)

    ckpt = torch.load(opt.ckpt, map_location='cpu')
    state_dict = ckpt['model']

    if torch.cuda.is_available():
        if torch.cuda.device_count() > 1:
            model.encoder = torch.nn.DataParallel(model.encoder)
        else:
            new_state_dict = {}
            # for k, v in state_dict.items():
            #     k = k.replace("module.", "")
            #     new_state_dict[k] = v
            # state_dict = new_state_dict
            # model = model.cuda()
            # classifier = classifier.cuda()
            # criterion = criterion.cuda()
            # cudnn.benchmark = True

        # model.load_state_dict(state_dict)
    else:
        print("GPU not available. Using CPU for inference.")
        model.load_state_dict(state_dict, map_location='cpu')

    return model, classifier, criterion


In [38]:
# Simulate the Opt object
class Opt:
    def __init__(self, val_folder, batch_size, num_workers, train_folder=None):
        self.val_folder = val_folder
        self.batch_size = batch_size
        self.num_workers = num_workers
        self.train_folder = train_folder

In [52]:
import torch
import torch.nn as nn
from torchvision import models
from main_linear import set_loader  # Replace with your actual data loader module
from networks.resnet_big import LinearClassifier
# Load your model and data loaders
# model = models.resnet50(pretrained=True)
# classifier = nn.Linear(2048, 4)  # Replace with your classifier architecture
# criterion = nn.CrossEntropyLoss()


opt = Opt(val_folder='./data/linear_prob_data/train/', batch_size=32, num_workers=4)

# Load the data loader
_, val_loader = set_loader(opt)

# Define class_to_idx based on your dataset
class_to_idx = {'African': 0, 'Asian': 1, 'Caucasian': 2, 'Indian': 3}
# Iterate through the small validation data loader and print labels
# for idx, (images, labels) in enumerate(val_loader):
#     print(f'Batch {idx} - Labels: {labels}')


# Create a small test dataset by taking the first N samples from the validation set
num_samples_to_test = 10  # Adjust this number as needed
small_val_loader = torch.utils.data.DataLoader(val_loader.dataset, batch_size=opt.batch_size, shuffle=True, num_workers=opt.num_workers)
small_val_loader.dataset.samples = small_val_loader.dataset.samples[:num_samples_to_test]

# Call the modified validate function with the small test dataset
loss, overall_accuracy, in_race_accuracies, out_of_race_accuracies = validate(val_loader, None, None, None, opt, class_to_idx)

# # Print the results
# print(f'Overall Accuracy: {overall_accuracy:.3f}')
# for race, in_race_acc in in_race_accuracies.items():
#     print(f'In-Race Accuracy ({race}): {in_race_acc:.3f}')
#     print(f'Out-of-Race Accuracy ({race}): {out_of_race_accuracies[race]:.3f}')

/Users/lorenzomendoza/anaconda3/envs/machinelearning/lib/python3.11/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/Users/lorenzomendoza/anaconda3/envs/machinelearning/lib/python3.11/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Batch 0 - Images: torch.Size([10, 3, 400, 400]), Labels: torch.Size([10]), Batch Size: 10
Labels Shape: torch.Size([10])
African
0
Asian
1
Caucasian
2
Indian
3
Race Labels: ['African']


TypeError: cannot unpack non-iterable NoneType object

i then want to those image_name,id,race,split
60-FaceId-0_align.jpg,m.07h5rn,0,test
62-FaceId-0_align.jpg,m.07h5rn,0,test
18-FaceId-0_align.jpg,m.07h5rn,0,test
19-FaceId-0_align.jpg,m.07h5rn,0,test
32-FaceId-0_align.jpg,m.07h5rn,0,test
50-FaceId-0_align.jpg,m.07h5rn,0,test
52-FaceId-0_align.jpg,m.07h5rn,0,test
101-FaceId-0_align.jpg,m.07h5rn,0,test
11-FaceId-0_align.jpg,m.07h5rn,0,test
35-FaceId-0_align.jpg,m.07h5rn,0,test
74-FaceId-0_align.jpg,m.07h5rn,0,test
78-FaceId-0_align.jpg,m.07h5rn,0,test
37-FaceId-0_align.jpg,m.07h5rn,0,train
85-FaceId-0_align.jpg,m.07h5rn,0,train
66-FaceId-0_align.jpg,m.07h5rn,0,train
106-FaceId-0_align.jpg,m.07h5rn,0,train
44-FaceId-0_align.jpg,m.07h5rn,0,train
63-FaceId-0_align.jpg,m.07h5rn,0,train
55-FaceId-0_align.jpg,m.07h5rn,0,train
70-FaceId-1_align.jpg,m.07h5rn,0,train
97-FaceId-0_align.jpg,m.07h5rn,0,train

In [ ]:
Helpe me do this: Now that we have the mapping from the labels to the races, we now want to track the performance of the accuracy on the races that the ids that were in the batch. 
To do this, we need to use label_to_race_mapping. target contains the labels for the true id of the images. label_to_race_mapping maps has the labels as keys mapping to it's race. 
After we get the Prediction and compare them to the targets to make correct, we should see how each race did from the labels of 

Prediction: tensor([[  0,   3,   1,   2, 398],
        [  0,   3,   1,   2, 398],
        [  0,   3,   1,   2, 325],
        [  0,   3,   1,   2, 355],
        [  0,   3,   1,   2, 355],
        [  0,   3,   1,   2, 227],
        [  0,   3,   1,   2, 355],
        [  0,   3,   1,   2, 341],
        [  0,   3,   1,   2, 212],
        [  0,   3,   1,   2, 227],
        [  0,   3,   1,   2, 341],
        [  0,   3,   1,   2, 212],
        [  0,   3,   1,   2, 398],
        [  0,   3,   1,   2, 341],
        [  0,   3,   1,   2, 341],
        [  0,   3,   1,   2, 341]], device='cuda:0')
Prediction T: tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0],
        [  3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
           3,   3],
        [  1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
           1,   1],
        [  2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
           2,   2],
        [398, 398, 325, 355, 355, 227, 355, 341, 212, 227, 341, 212, 398, 341,
         341, 341]], device='cuda:0')
target_viewed T: tensor([[0, 2, 2, 3, 2, 3, 0, 2, 1, 3, 1, 2, 3, 0, 1, 1]], device='cuda:0')
target_expand_pred T: tensor([[0, 2, 2, 3, 2, 3, 0, 2, 1, 3, 1, 2, 3, 0, 1, 1],
        [0, 2, 2, 3, 2, 3, 0, 2, 1, 3, 1, 2, 3, 0, 1, 1],
        [0, 2, 2, 3, 2, 3, 0, 2, 1, 3, 1, 2, 3, 0, 1, 1],
        [0, 2, 2, 3, 2, 3, 0, 2, 1, 3, 1, 2, 3, 0, 1, 1],
        [0, 2, 2, 3, 2, 3, 0, 2, 1, 3, 1, 2, 3, 0, 1, 1]], device='cuda:0')
correct: tensor([[ True, False, False, False, False, False,  True, False, False, False,
         False, False, False,  True, False, False],
        [False, False, False,  True, False,  True, False, False, False,  True,
         False, False,  True, False, False, False],
        [False, False, False, False, False, False, False, False,  True, False,
          True, False, False, False,  True,  True],
        [False,  True,  True, False,  True, False, False,  True, False, False,
         False,  True, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False]], device='cuda:0')
k: 1
correct_k: tensor([3.], device='cuda:0')
k: 5
correct_k: tensor([16.], device='cuda:0')


def accuracy(output, target, label_to_race_mapping ,topk=(1,)): # Need to add label_to_race_mapping PARAM
    """Computes the accuracy over the k top predictions for the specified values of k, and records accuracy by race"""
    with torch.no_grad():
        maxk = max(topk)
        batch_size = target.size(0)

        _, pred = output.topk(maxk, 1, True, True)
        print(f"Prediction: {pred}")
        pred = pred.t()
        print(f"Prediction T: {pred}")

        target_viewed = target.view(1, -1)
        print(f"target_viewed T: {target_viewed}")

        target_expand_pred = target_viewed.expand_as(pred)
        print(f"target_expand_pred T: {target_expand_pred}")

        correct = pred.eq(target_expand_pred)
        print(f"correct: {correct}")

        res = []
        for k in topk: 
            correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True)
            res.append(correct_k.mul_(100.0 / batch_size)) # Right now 
        return res

def label_to_race(labels, id_to_idx, class_to_race):
    id_list = labels.tolist() 
    print(f"id_list: {id_list}")

    # this is a list of id is the image from, 0 (e.g., 'm.0181j_'), and the remaining 4 images belong to class 1 (e.g., 'm.01lb8z').
    # id_list: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1]
    
    class_labels = [class_label for idx in id_list for class_label, class_idx in id_to_idx.items() if class_idx == idx] # Get the list of corresponding ids that the images are from
    # id_list: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1]
    # -> Class: ['m.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.01lb8z', 'm.01lb8z', 'm.01lb8z', 'm.01lb8z']
    races = [class_to_race[class_label] for class_label in class_labels] # Now map the ids to the race from the csv
    print(f"Class: {class_labels}")
    print(f"Races: {races}")
    # Create a dictionary mapping labels to their corresponding races
    label_to_race_mapping = dict(zip(id_list, races))
    print(f"Label-to-Race{label_to_race_mapping}")

    return label_to_race_mapping
    

def validate(val_loader, model, classifier, criterion, opt):
    """validation"""
    model.eval()
    classifier.eval()
    id_to_idx = val_loader.dataset.class_to_idx # map of id to indices in the val set
    print(f"id_to_idx: {id_to_idx}")

    batch_time = AverageMeter()
    losses = AverageMeter()
    top1 = AverageMeter()

    # Read the CSV file and create a mapping from class labels to races
    class_to_race = {} 
    with open('data.csv', 'r') as csvfile:
        csvreader = csv.DictReader(csvfile)
        for row in csvreader:
            class_to_race[row['id']] = row['race']

    with torch.no_grad():
        end = time.time()
        for idx, (images, labels) in enumerate(val_loader):
            images = images.float().cuda()
            labels = labels.cuda()
            races = label_to_race(labels, id_to_idx, class_to_race)

            bsz = labels.shape[0]

            # forward
            output = classifier(model.encoder(images))
            loss = criterion(output, labels)

            # update metric
            losses.update(loss.item(), bsz)
            acc1, acc5 = accuracy(output, labels, topk=(1, 5))
            top1.update(acc1[0], bsz)



            # measure elapsed time
            batch_time.update(time.time() - end)
            end = time.time()

            if idx % opt.print_freq == 0:
                print('Test: [{0}/{1}]\t'
                      'Time {batch_time.val:.3f} ({batch_time.avg:.3f})\t'
                      'Loss {loss.val:.4f} ({loss.avg:.4f})\t'
                      'Acc@1 {top1.val:.3f} ({top1.avg:.3f})'.format(
                       idx, len(val_loader), batch_time=batch_time,
                       loss=losses, top1=top1))

    print(' * Acc@1 {top1.avg:.3f}'.format(top1=top1))
    return losses.avg, top1.avg


In [ ]:
from __future__ import print_function

import sys
import argparse
import time
import math

import torch
import torch.backends.cudnn as cudnn
import pandas as pd
from torchvision import transforms, datasets

from util import AverageMeter
from util import adjust_learning_rate, warmup_learning_rate, accuracy
from util import set_optimizer
from networks.resnet_big import SupConResNet, LinearClassifier

try:
    import apex
    from apex import amp, optimizers
except ImportError:
    pass
'''
python3 main_linear.py --batch_size 16 --num_workers 8 --learning_rate 0.5 --epochs 2 --cosine --dataset path --train_folder ./data/train --val_folder ./data/test/African --cur_race African --n_cls 500
'''

def parse_option():
    parser = argparse.ArgumentParser('argument for training')

    parser.add_argument('--print_freq', type=int, default=10,
                        help='print frequency')
    parser.add_argument('--save_freq', type=int, default=50,
                        help='save frequency')
    parser.add_argument('--batch_size', type=int, default=256,
                        help='batch_size')
    parser.add_argument('--num_workers', type=int, default=8,
                        help='num of workers to use')
    parser.add_argument('--epochs', type=int, default=100,
                        help='number of training epochs')

    # optimization
    parser.add_argument('--learning_rate', type=float, default=0.1,
                        help='learning rate')
    parser.add_argument('--lr_decay_epochs', type=str, default='60,75,90',
                        help='where to decay lr, can be a list')
    parser.add_argument('--lr_decay_rate', type=float, default=0.2,
                        help='decay rate for learning rate')
    parser.add_argument('--weight_decay', type=float, default=0,
                        help='weight decay')
    parser.add_argument('--momentum', type=float, default=0.9,
                        help='momentum')

    # model dataset
    parser.add_argument('--model', type=str, default='resnet50')
    parser.add_argument('--dataset', type=str, default='path',
                        choices=['path', 'cifar10', 'cifar100'], help='dataset')
    parser.add_argument('--n_cls', type=int, help='number of classes')
    parser.add_argument('--train_folder', type=str, help='path to train folder')
    parser.add_argument('--val_folder', type=str, help='path to val folder')
    parser.add_argument('--cur_race', type=str, choices=['Caucasian', 'African', 'Asian', 'Indian'], help="enter race currently testing")

    # other setting
    parser.add_argument('--cosine', action='store_true',
                        help='using cosine annealing')
    parser.add_argument('--warm', action='store_true',
                        help='warm-up for large batch training')

    parser.add_argument('--ckpt', type=str, default='',
                        help='path to pre-trained model')

    opt = parser.parse_args()

    # set the path according to the environment
    # opt.data_folder = './datasets/'

    iterations = opt.lr_decay_epochs.split(',')
    opt.lr_decay_epochs = list([])
    for it in iterations:
        opt.lr_decay_epochs.append(int(it))

    opt.model_name = '{}_{}_lr_{}_decay_{}_bsz_{}'.\
        format(opt.dataset, opt.model, opt.learning_rate, opt.weight_decay,
               opt.batch_size)

    if opt.cosine:
        opt.model_name = '{}_cosine'.format(opt.model_name)

    # warm-up for large-batch training,
    if opt.warm:
        opt.model_name = '{}_warm'.format(opt.model_name)
        opt.warmup_from = 0.01
        opt.warm_epochs = 10
        if opt.cosine:
            eta_min = opt.learning_rate * (opt.lr_decay_rate ** 3)
            opt.warmup_to = eta_min + (opt.learning_rate - eta_min) * (
                    1 + math.cos(math.pi * opt.warm_epochs / opt.epochs)) / 2
        else:
            opt.warmup_to = opt.learning_rate

    if opt.dataset == 'path':
        assert opt.train_folder is not None \
            and opt.val_folder is not None \
            and opt.n_cls is not None \
            and opt.cur_race is not None

    return opt

def set_loader(opt):
    #get train and val loader
    input_shape = [3, 128, 128]
    train_transform = transforms.Compose([
        transforms.Resize(int(input_shape[1] * 156 / 128)),
        transforms.RandomCrop(input_shape[1:]),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.5, 0.5, 0.5],
                        std=[0.5, 0.5, 0.5])
    ])  

    val_transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.5, 0.5, 0.5],
                        std=[0.5, 0.5, 0.5])
    ])

    if opt.train_folder is not None:
        train_dataset = datasets.ImageFolder(
            root=opt.train_folder,
            transform=train_transform
        )
        train_loader = torch.utils.data.DataLoader(
            train_dataset, batch_size=opt.batch_size, shuffle=True,
            num_workers=opt.num_workers, pin_memory=True)
    else:
        train_loader = None

    val_dataset = datasets.ImageFolder(
        root=opt.val_folder,
        transform=val_transform
    )

    val_loader = torch.utils.data.DataLoader(
        val_dataset, batch_size=opt.batch_size, shuffle=False,
        num_workers=opt.num_workers, pin_memory=True)

    return train_loader, val_loader



import os

def set_model(opt):
    model = SupConResNet(name=opt.model)
    criterion = torch.nn.CrossEntropyLoss()

    classifier = LinearClassifier(name=opt.model, num_classes=opt.n_cls)

    # Check if the checkpoint file exists
    if os.path.isfile(opt.ckpt):
        ckpt = torch.load(opt.ckpt, map_location='cpu')
        state_dict = ckpt['model']
    else:
        print(f"No checkpoint found at {opt.ckpt}")
        state_dict = None

    if torch.cuda.is_available():
        if torch.cuda.device_count() > 1:
            model.encoder = torch.nn.DataParallel(model.encoder)
        elif state_dict is not None:  # Add this line
            new_state_dict = {}
            for k, v in state_dict.items():
                k = k.replace("module.", "")
                new_state_dict[k] = v
            state_dict = new_state_dict
        model = model.cuda()
        classifier = classifier.cuda()
        criterion = criterion.cuda()
        cudnn.benchmark = True

        # Load the state dict only if it is not None
        if state_dict is not None:
            model.load_state_dict(state_dict)

    else:
        raise NotImplementedError('This code requires GPU')

    return model, classifier, criterion



def train(train_loader, model, classifier, criterion, optimizer, epoch, opt):
    """one epoch training"""
    model.eval()
    classifier.train()

    batch_time = AverageMeter()
    data_time = AverageMeter()
    losses = AverageMeter()
    top1 = AverageMeter()

    end = time.time()
    for idx, (images, labels) in enumerate(train_loader):
        data_time.update(time.time() - end)

        images = images.cuda(non_blocking=True)
        labels = labels.cuda(non_blocking=True)
        bsz = labels.shape[0]

        # warm-up learning rate
        warmup_learning_rate(opt, epoch, idx, len(train_loader), optimizer)

        # compute loss
        with torch.no_grad():
            features = model.encoder(images)
        output = classifier(features.detach())
        loss = criterion(output, labels)

        # update metric
        losses.update(loss.item(), bsz)
        acc1, acc5 = accuracy(output, labels, topk=(1, 5))
        top1.update(acc1[0], bsz)

        # SGD
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # measure elapsed time
        batch_time.update(time.time() - end)
        end = time.time()

        # print info
        if (idx + 1) % opt.print_freq == 0:
            print('Train: [{0}][{1}/{2}]\t'
                  'BT {batch_time.val:.3f} ({batch_time.avg:.3f})\t'
                  'DT {data_time.val:.3f} ({data_time.avg:.3f})\t'
                  'loss {loss.val:.3f} ({loss.avg:.3f})\t'
                  'Acc@1 {top1.val:.3f} ({top1.avg:.3f})'.format(
                   epoch, idx + 1, len(train_loader), batch_time=batch_time,
                   data_time=data_time, loss=losses, top1=top1))
            sys.stdout.flush()

    return losses.avg, top1.avg


def label_to_race(labels, id_to_idx, class_to_race):
    id_list = labels.tolist() 
    # print(f"id_list: {id_list}")

    # this is a list of id is the image from, 0 (e.g., 'm.0181j_'), and the remaining 4 images belong to class 1 (e.g., 'm.01lb8z').
    # id_list: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1]
    
    class_labels = [class_label for idx in id_list for class_label, class_idx in id_to_idx.items() if class_idx == idx] # Get the list of corresponding ids that the images are from
    # id_list: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1]
    # -> Class: ['m.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.01lb8z', 'm.01lb8z', 'm.01lb8z', 'm.01lb8z']
    races = [class_to_race[class_label] for class_label in class_labels] # Now map the ids to the race from the csv
    # print(f"Class: {class_labels}")
    # print(f"Races: {races}")
    # Create a dictionary mapping labels to their corresponding races
    label_to_race_mapping = dict(zip(id_list, races))
    # print(f"Label-to-Race{label_to_race_mapping}")

    return label_to_race_mapping

import csv
def validate(val_loader, model, classifier, criterion, opt):
    """validation"""
    model.eval()
    classifier.eval()
    id_to_idx = val_loader.dataset.class_to_idx # map of id to indices in the val set
    # print(f"id_to_idx: {id_to_idx}")

    batch_time = AverageMeter()
    losses = AverageMeter()
    top1 = AverageMeter()

    # Read the CSV file and create a mapping from class labels to races
    class_to_race = {} 
    with open('./data/linear_prob_dataset_split.csv', 'r') as csvfile:
        csvreader = csv.DictReader(csvfile)
        for row in csvreader:
            class_to_race[row['id']] = row['race']

    with torch.no_grad():
        end = time.time()
        for idx, (images, labels) in enumerate(val_loader):
            images = images.float().cuda()
            labels = labels.cuda()
            labels_to_races = label_to_race(labels, id_to_idx, class_to_race)

            bsz = labels.shape[0]
            # print(f'Batch {idx} - Images: {images.shape}, Labels: {labels.shape}, Batch Size: {bsz}')

            # forward
            output = classifier(model.encoder(images))
            loss = criterion(output, labels)
            # print(f'labels: {labels}')

            # print(f'Output: {output}')

            # update metric
            losses.update(loss.item(), bsz)
            # acc1, acc5 = accuracy(output, labels, topk=(1, 5))
            print(f"labels_to_races: {labels_to_races}")
            acc1, accuracy_by_race = accuracy(output, labels, topk=(1,), label_to_race_mapping = labels_to_races)
                # accuracy_by_race = {race: correct / total if total > 0 else 0 
                #         for race, correct, total in zip(correct_by_race.keys(), correct_by_race.values(), total_by_race.values())}

            top1.update(acc1[0][0], bsz)
            # print(acc1[0][0])
            print(f"accuracy_by_race: {accuracy_by_race}")

            # measure elapsed time
            batch_time.update(time.time() - end)
            end = time.time()

            if idx % opt.print_freq == 0:
                print('Test: [{0}/{1}]\t'
                      'Time {batch_time.val:.3f} ({batch_time.avg:.3f})\t'
                      'Loss {loss.val:.4f} ({loss.avg:.4f})\t'
                      'Acc@1 {top1.val:.3f} ({top1.avg:.3f})'.format(
                      idx, len(val_loader), batch_time=batch_time,
                      loss=losses, top1=top1))
                for race, acc in accuracy_by_race.items():
                    print(f'Accuracy for {race}: {acc:.3f}')


    print(' * Acc@1 {top1.avg:.3f}'.format(top1=top1))
    
    return losses.avg, top1.avg


def main():
    best_acc = 0
    opt = parse_option()

    # build data loader
    train_loader, val_loader = set_loader(opt)

    # build model and criterion
    model, classifier, criterion = set_model(opt)

    # build optimizer
    optimizer = set_optimizer(opt, classifier)

    # training routine
    for epoch in range(1, opt.epochs + 1):
        adjust_learning_rate(opt, optimizer, epoch)

        # train for one epoch
        time1 = time.time()
        loss, acc = train(train_loader, model, classifier, criterion,
                          optimizer, epoch, opt)
        time2 = time.time()
        print('Train epoch {}, total time {:.2f}, accuracy: {:.2f}'.format(
            epoch, time2 - time1, acc))

        # eval for one epoch
        loss, val_acc = validate(val_loader, model, classifier, criterion, opt)
        if val_acc > best_acc:
            best_acc = val_acc

        # Save checkpoint after each epoch
        checkpoint = {
            'epoch': epoch,
            'state_dict': model.state_dict(),
            'best_acc': best_acc,
            'optimizer': optimizer.state_dict(),
        }
        torch.save(checkpoint, 'checkpoint_epoch_{}.pth'.format(epoch))

    print('best accuracy: {:.2f}'.format(best_acc))

if __name__ == '__main__':
    main()


In [ ]:
"""

id_to_idx: {'m.0181j_': 0, 'm.01lb8z': 1, 'm.020skv': 2, 'm.0240pk': 3, 'm.03tjn_': 4, 'm.07h5rn': 5, 'm.09d6n9': 6, 'm.09fdg1': 7, 'm.0bb8pbs': 8, 'm.0cc99yf': 9}
id_list: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1]
Class: ['m.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.01lb8z', 'm.01lb8z', 'm.01lb8z', 'm.01lb8z']
Races: ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']

"""

def label_to_race(labels, id_to_idx, class_to_race):
    id_list = labels.tolist() 
    print(f"id_list: {id_list}")

    # this is a list of id is the image from, 0 (e.g., 'm.0181j_'), and the remaining 4 images belong to class 1 (e.g., 'm.01lb8z').
    # id_list: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1]
    
    class_labels = [class_label for idx in id_list for class_label, class_idx in id_to_idx.items() if class_idx == idx] # Get the list of corresponding ids that the images are from
    # id_list: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1]
    # -> Class: ['m.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.0181j_', 'm.01lb8z', 'm.01lb8z', 'm.01lb8z', 'm.01lb8z']
    races = [class_to_race[class_label] for class_label in class_labels] # Now map the ids to the race from the csv
    print(f"Class: {class_labels}")
    print(f"Races: {races}")
    return races